# Pandas Basic

### Pandas is a wrapper of two languages:

In [1]:
import pandas as pd
import numpy as np

In [2]:
print('Pandas: ', pd.__version__)
print('Numpy: ', np.__version__)

Pandas:  3.0.2
Numpy:  2.4.4

# Pandas Data Structures
 - Series - Single dimensional data structure. Similar to a list or a single column
   - homogenous (of the same data type)
 - DataFrame - multidimensional table
   - heterogenous (of many datatypes)

In [3]:
ser1 = pd.Series([10, 20,30,40], index=['A', 'B', 'C', 'D'])
print(ser1)

A    10
B    20
C    30
D    40
dtype: int64

In [4]:
# Creating a series from a preexisting dictionary

d = {
    'b': 1,
    'a': 0,
    'c': 2,
    'd':10
}

ser2 = pd.Series(d)

In [5]:
d1 = {
    'a':0.0,
    'b':1.0,
    'c':2.0
}

ser3 = pd.Series(d1)

print(ser3)

a    0.0
b    1.0
c    2.0
dtype: float64

In [6]:
calories = {
    'day1': 700,
    'day2': 2500,
    'day3': 1200
}

# Use indexes to choose certain values for a series
ser4 = pd.Series(calories, index = ['day1', 'day2'])

print(ser4)

day1     700
day2    2500
dtype: int64

In [7]:
# If provided a scalar values, value will repeat to fill all index labels
ser5 = pd.Series(5.0, index=['a', 'b', 'c'])
print(ser5)

a    5.0
b    5.0
c    5.0
dtype: float64

### Data Frames:
-  indexes (each record)
-  columns (each variables)

In [8]:
fruit_data = {
    'apple_sales': [3, 2, 0, 2, 9, 4, 7, 2],
    'orange_sales': [0, 3, 2, 7, 7, 8, 3, 0]
}

idx = pd.RangeIndex(2000, 2008) # dynamically create a range of indexes
purchases = pd.DataFrame(fruit_data, index = idx)

print(purchases)

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

In [9]:
rows, cols = purchases.shape
print('Rows: ', rows)
print('Columns: ', cols)

Rows:  8
Columns:  2

In [10]:
# To view the top n elements, by default gives 5 elements
print(purchases.head())

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7

In [11]:
# To view the bottom n elements, by default 5

print(purchases.tail())

      apple_sales  orange_sales
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

### Importing FIles with Pandas
-   `.read_csv()`
-   `.read_excel()`
-   `.read_json()`
-   `.read_sql()`

In [12]:
# Reads employee into and pandas df
employee_df = pd.read_csv('data/employee.csv')

employee_df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [13]:
rows, cols = employee_df.shape

print('Rows: ', rows)
print('Cols: ', cols)

Rows:  15
Cols:  4

In [14]:
employee_df.dtypes

Name          str
Age       float64
Weight    float64
Salary    float64
dtype: object

### EDA - Exploratory Data Analysis - The first look (Step 1 of data preparation)
-   Data Profiling
    -   Structure (shape)
    -   quality (missing values, duplicates, unique values)
    -   Content (data types, ranges, dispersion, measure central tendency) 
-   Profiling Techniques
    -   Data type and format validation 
    -   Statistical summaries (descriptive stats, values counts, frequency checks)
    -   Uniqueness and Cardinality
    -   Pattern Recognition
    -   Cross Validation

In [15]:
# Importing JSON data
cars_df = pd.read_json('data/cars.json')

cars_df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [16]:
rows, cols = cars_df.shape

print('Rows: ', rows)
print('Cols: ', cols)

Rows:  161
Cols:  11

In [17]:
cars_df.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

In [18]:
# Getting a brief overview of descriptive statistics (Quantitative Data)
cars_df.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,quantity
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,23.801863,5.347826,185.232919,100.664596,2915.093168,15.509938,76.260870,224.875776
std,8.810125,1.761607,105.394809,41.079640,890.293883,2.515780,3.818576,127.741084
min,0.000000,3.000000,68.000000,0.000000,1613.000000,8.000000,70.000000,5.000000
25%,17.000000,4.000000,98.000000,72.000000,2130.000000,14.000000,73.000000,112.000000
50%,24.000000,4.000000,140.000000,88.000000,2625.000000,15.500000,76.000000,227.000000
75%,31.000000,8.000000,302.000000,130.000000,3620.000000,17.100000,80.000000,337.000000
max,46.600000,8.000000,440.000000,215.000000,4955.000000,22.100000,82.000000,439.000000

In [19]:
# Value counts of categorical data
cars_df['city'].value_counts()

city
NewYork    36
NJ         35
DALLAS     33
TEXAS      30
OH         27
Name: count, dtype: int64

In [20]:
cars_df['city'].unique()

<StringArray>
['NJ', 'DALLAS', 'TEXAS', 'OH', 'NewYork']
Length: 5, dtype: str

In [21]:
cars_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           161 non-null    str
 1   MPG           161 non-null    float64
 2   Cylinders     161 non-null    int64
 3   Displacement  161 non-null    float64
 4   Horsepower    161 non-null    int64
 5   Weight        161 non-null    int64
 6   Acceleration  161 non-null    float64
 7   Model         161 non-null    int64
 8   Origin        161 non-null    str
 9   quantity      161 non-null    int64
 10  city          161 non-null    str
dtypes: float64(3), int64(5), str(3)
memory usage: 14.0 KB

In [22]:
cars_df.count()

Car             161
MPG             161
Cylinders       161
Displacement    161
Horsepower      161
Weight          161
Acceleration    161
Model           161
Origin          161
quantity        161
city            161
dtype: int64

In [23]:
cars_df.head(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS

In [24]:
cars_df.tail(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
159,Mercury Lynx l,36.0,4,98.0,70,2125,17.3,82,US,425,TEXAS
160,Mercury Marquis,11.0,8,429.0,208,4633,11.0,72,US,112,OH

In [25]:
# .at method to grab specific values from dataset using the label
cars_df.at[159, 'MPG']

np.float64(36.0)

In [26]:
# .at method to grab specific values from dataset using the index number
cars_df.iat[159, 1]

np.float64(36.0)

In [27]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}
student_df = pd.DataFrame(student_dict)
print(student_df)

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

In [28]:
student_df.describe()

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000

In [29]:
list_index = student_df.columns
print(list_index)

Index(['Name', 'Age', 'Marks'], dtype='str')

In [30]:
label1 = student_df.columns[0]
print(label1)

Name

In [31]:
# Getting column names as lists for looping
labels_as_list = student_df.columns.to_list()
print(labels_as_list)

['Name', 'Age', 'Marks']

### EDA with a CSV

In [32]:
e_df = pd.read_csv('data/employee.csv')
e_df.head(10)

       Name   Age  Weight     Salary
0     James  36.0    75.0  5428000.0
1   Villers  38.0    74.0  3428000.0
2     VKole  31.0    70.0  8428000.0
3     Smith  34.0    80.0  4428000.0
4     Gayle  40.0   100.0  4528000.0
5      Adam  40.0     NaN  4528000.0
6    Rooter  33.0    72.0  7028000.0
7  Peterson  42.0    85.0  2528000.0
8     lynda  42.0    85.0        NaN
9       NaN  42.0    85.0        NaN

In [33]:
e_df.tail(2)

    Name   Age  Weight     Salary
13  John  41.0    85.0  1528000.0
14   Ali  26.0    69.0        NaN

In [34]:
e_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    14 non-null     str
 1   Age     12 non-null     float64
 2   Weight  14 non-null     float64
 3   Salary  12 non-null     float64
dtypes: float64(3), str(1)
memory usage: 612.0 bytes

In [35]:
rows, cols = e_df.shape
print('Rows:', rows, 'Columns:', cols)

Rows: 15 Columns: 4

In [36]:
e_df2 = pd.read_csv('data/employee.csv', skiprows=5, header=None)
e_df2

           0     1      2          3
0      Gayle  40.0  100.0  4528000.0
1       Adam  40.0    NaN  4528000.0
2     Rooter  33.0   72.0  7028000.0
3   Peterson  42.0   85.0  2528000.0
4      lynda  42.0   85.0        NaN
5        NaN  42.0   85.0        NaN
6      Jenny   NaN  100.0    25632.0
7       Kenn   NaN  110.0    25632.0
8        Aly   NaN   90.0    25582.0
9       John  41.0   85.0  1528000.0
10       Ali  26.0   69.0        NaN

In [37]:
# Get only specific columns from csv
# e_df3 = pd.read_csv('data/employee.csv', usecols=['Name', 'Salary']) # Based on labels

e_df3 = pd.read_csv('data/employee.csv', usecols=[0, 3]) # Based on index numbers
e_df3

        Name     Salary
0      James  5428000.0
1    Villers  3428000.0
2      VKole  8428000.0
3      Smith  4428000.0
4      Gayle  4528000.0
5       Adam  4528000.0
6     Rooter  7028000.0
7   Peterson  2528000.0
8      lynda        NaN
9        NaN        NaN
10     Jenny    25632.0
11      Kenn    25632.0
12       Aly    25582.0
13      John  1528000.0
14       Ali        NaN

### Selecting columns using pandas

In [38]:
df_cars = pd.read_json('data/cars.json')
df_cars.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [39]:
# df_cars.columns[0] accessing a single value, sigle bracket


df_cars.columns[[0, 1, 9]] # Accessing multiple values, double brackets

Index(['Car', 'MPG', 'quantity'], dtype='str')

In [40]:
# Accessing a series using a lable
df_cars['Car']

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [41]:
# Accessing a series using an index number
df_cars[df_cars.columns[0]]

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [42]:
df_cars[['Car', 'MPG', 'quantity']]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

In [43]:
# Grab a subset of dataframe with index numbers
df_cars[df_cars.columns[[0, 1, 9]]]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

### Frequency Analysis - Value Count

In [44]:
# Sample DataFrame
data = {'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing']}

cat_df = pd.DataFrame(data)

# .calue_counts()

cat_df.value_counts()

Category
Electronics    2
Clothing       2
Books          2
Name: count, dtype: int64

In [45]:
# Create the dataframe
sales_data={"Devices":['Laptop','iPhone','LED','LCD','Smart-Phone','Washing-Machine'],
           'Brand':['Lenovo','Apple','Samsung','Samsung','Samsung','Whirpool'],
           'Sales':[1000,2000,4000,2000,1000,4000],
           'Profit':[500,1000,1000,1500,1000,1500],
           'Pices left':[5000,4000,4000,5000,5000,1000]}

sales_df = pd.DataFrame(sales_data)

# Get frequency count for brands
frequency = sales_df['Brand'].value_counts()
print(frequency)

frequent_product = frequency[frequency > 1].index[0]

print(frequent_product)

Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64
Samsung

In [46]:
data = {'Score': [85, 92, 88, 75, None, 90, None, 85]}

scores_df = pd.DataFrame(data)

In [47]:
score_counts = scores_df.value_counts(dropna=False)
print('Score:', score_counts)

Score: Score
85.0     2
NaN      2
92.0     1
88.0     1
75.0     1
90.0     1
Name: count, dtype: int64

### Sort using Pandas
-   `.sort_values()`

In [48]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
       'Score 1' : [56,86,77,45],
       'Score 2' : [50,96,60,30]}

grades_df = pd.DataFrame(data)

grades_df.head()

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [49]:
grades_df = grades_df.assign(address=['NYC', 'NJ', 'CA', 'PA'])
grades_df.head()

     Name  Height Qualification  Score 1  Score 2 address
0    Jane     5.1           Msc       56       50     NYC
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
3    Fadi     5.2           Msc       45       30      PA

In [50]:
# Sort_values(). sorts by assending by default
print(grades_df.sort_values(by='Score 1'))

     Name  Height Qualification  Score 1  Score 2 address
3    Fadi     5.2           Msc       45       30      PA
0    Jane     5.1           Msc       56       50     NYC
2   James     5.1           Msc       77       60      CA
1  Princi     6.2            MA       86       96      NJ

In [51]:
print(grades_df.sort_values(by='Score 1', ascending=False))

     Name  Height Qualification  Score 1  Score 2 address
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
0    Jane     5.1           Msc       56       50     NYC
3    Fadi     5.2           Msc       45       30      PA

In [52]:
cars = pd.read_json('data/cars.json')
cars.head(15)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork
5,Chevy C20,10.0,8,307.0,200,4376,15.0,70,US,70,NJ
6,Chevy S-10,31.0,4,119.0,82,2720,19.4,82,US,7,NewYork
7,Chrysler Cordoba,15.5,8,400.0,190,4325,12.2,77,US,7,NJ
8,Chrysler Lebaron Medallion,26.0,4,156.0,92,2585,14.5,82,US,434,DALLAS
9,Chrysler Lebaron Salon,17.6,6,225.0,85,3465,16.6,81,US,412,TEXAS
10,Chrysler Lebaron Town @ Country (sw),18.5,8,360.0,150,3940,13.0,79,US,337,OH
11,Chrysler New Yorker Brougham,13.0,8,440.0,215,4735,11.0,73,US,139,NewYork
12,Chrysler Newport Royal,13.0,8,400.0,190,4422,12.5,72,US,115,NJ
13,Citroen DS-21 Pallas,0.0,4,133.0,115,3090,17.5,70,Europe,58,DALLAS
14,Datsun 1200,35.0,4,72.0,69,1613,18.0,71,Japan,99,TEXAS

In [53]:
print(cars.sort_values(by='quantity'))

                            Car   MPG  Cylinders  Displacement  Horsepower  \
123                 Ford Torino  17.0          8         302.0         140
112         Ford Mustang II 2+2  25.5          4         140.0          89
6                    Chevy S-10  31.0          4         119.0          82
7              Chrysler Cordoba  15.5          8         400.0         190
121                 Ford Ranger  28.0          4         120.0          79
..                          ...   ...        ...           ...         ...
128                Honda Accord  36.0          4         107.0          75
134          Honda Civic (auto)  32.0          4          91.0          67
22                Datsun 310 GX  38.0          4          91.0          67
8    Chrysler Lebaron Medallion  26.0          4         156.0          92
110             Ford Mustang GL  27.0          4         140.0          86

     Weight  Acceleration  Model Origin  quantity     city
123    3449          10.5     70     US         5       OH
112    2755          15.8     77     US         5       NJ
6      2720          19.4     82     US         7  NewYork
7      4325          12.2     77     US         7       NJ
121    2625          18.6     82     US         7   DALLAS
..      ...           ...    ...    ...       ...      ...
128    2205          14.5     82  Japan       427       OH
134    1965          15.7     82  Japan       430    TEXAS
22     1995          16.2     82  Japan       431       NJ
8      2585          14.5     82     US       434   DALLAS
110    2790          15.6     82     US       439       OH

[161 rows x 11 columns]

In [54]:
print(cars.sort_values(by=['quantity', 'Car'], ascending=[False, True]))

                            Car   MPG  Cylinders  Displacement  Horsepower  \
110             Ford Mustang GL  27.0          4         140.0          86
8    Chrysler Lebaron Medallion  26.0          4         156.0          92
22                Datsun 310 GX  38.0          4          91.0          67
134          Honda Civic (auto)  32.0          4          91.0          67
128                Honda Accord  36.0          4         107.0          75
..                          ...   ...        ...           ...         ...
121                 Ford Ranger  28.0          4         120.0          79
130             Honda Accord LX  29.5          4          98.0          68
147            Mazda GLC Deluxe  34.1          4          86.0          65
112         Ford Mustang II 2+2  25.5          4         140.0          89
123                 Ford Torino  17.0          8         302.0         140

     Weight  Acceleration  Model Origin  quantity    city
110    2790          15.6     82     US       439      OH
8      2585          14.5     82     US       434  DALLAS
22     1995          16.2     82  Japan       431      NJ
134    1965          15.7     82  Japan       430   TEXAS
128    2205          14.5     82  Japan       427      OH
..      ...           ...    ...    ...       ...     ...
121    2625          18.6     82     US         7  DALLAS
130    2135          16.6     78  Japan         7      NJ
147    1975          15.2     79  Japan         7      NJ
112    2755          15.8     77     US         5      NJ
123    3449          10.5     70     US         5      OH

[161 rows x 11 columns]

### Slicing a df with .iloc() & .loc()
-   `df.loc[row:row, col:col]` - label based indexing
-   `df.iloc[row:row, col:col]` - index based location

In [55]:
# Initializing the nested list with Data set
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['John', 41, 85, 1528000],

]

e_df = pd.DataFrame(employee_list, columns=['Name', 'Age', 'Weight', 'Salary'])

e_df.head()

      Name  Age  Weight   Salary
0    James   36      75  5428000
1  Villers   38      74  3428000
2    VKole   31      70  8428000
3    Smith   34      80  4428000
4    Gayle   40     100  4528000

In [56]:
# Grabs the first row
e_df.iloc[0:1]

    Name  Age  Weight   Salary
0  James   36      75  5428000

In [57]:
# Grabs the first 4 rows
e_df.iloc[0:4]

      Name  Age  Weight   Salary
0    James   36      75  5428000
1  Villers   38      74  3428000
2    VKole   31      70  8428000
3    Smith   34      80  4428000

In [58]:
# Grabs all rows but only the first 3 columns
e_df.iloc[:, :3]

       Name  Age  Weight
0     James   36      75
1   Villers   38      74
2     VKole   31      70
3     Smith   34      80
4     Gayle   40     100
5    Rooter   33      72
6  Peterson   42      85
7      John   41      85

In [59]:
# Grabs first 2 rows and the first 2 columns
e_df.iloc[:2, :2]

      Name  Age
0    James   36
1  Villers   38

In [60]:
basketball = {'team': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
                   'points': [18, 22, 19, 14, 14, 11, 20, 28],
                   'assists': [5, 7, 7, 9, 12, 9, 9, 4],
                   'rebounds': [11, 8, 10, 6, 6, 5, 9, 12],
                   'steals': [4, 3, 3, 2, 5, 4, 3, 8],
                   'blocks': [1, 0, 0, 3, 2, 2, 1, 5]
}

ball_up = pd.DataFrame(basketball)

ball_up.head()

  team  points  assists  rebounds  steals  blocks
0    A      18        5        11       4       1
1    B      22        7         8       3       0
2    C      19        7        10       3       0
3    D      14        9         6       2       3
4    E      14       12         6       5       2

In [61]:
# Locate all rows and columns team, rebounds
ball_up.loc[: , ['team', 'rebounds']]

  team  rebounds
0    A        11
1    B         8
2    C        10
3    D         6
4    E         6
5    F         5
6    G         9
7    H        12

In [62]:
# Select values from rows 3 - 6 and show the team name

ball_up.loc[3:6, ['team']]

  team
3    D
4    E
5    F
6    G


### Handling Missing Values
-   `df.isnull()`- to detect missing values (`.isna()`)
-   `df.fillna()` - to fill missing values
-   `df.dropna()` - to remove missing values
-   `df.replace()` - to replace specific values (imputation)

### Pandas Date & Time 
-   `pd.to_datetime()`- to convert different data types into datetime object
-   `pd.date_range()`- used to generate a range of date and time 
-   `pd.timestamp()` - generate the time expressed as number of seconds since 01/01/1970

In [63]:
# Generate a range of dates from start to end default frequency
# periods = the number of dates you want between the start and end (inclusive)
date_range = pd.date_range(start='04/05/2023', end='05/05/2026', periods=5)
print(date_range)

DatetimeIndex(['2023-04-05 00:00:00', '2024-01-11 12:00:00',
               '2024-10-19 00:00:00', '2025-07-27 12:00:00',
               '2026-05-05 00:00:00'],
              dtype='datetime64[us]', freq=None)

In [64]:
date_range = pd.date_range(start='01/01/2020', end='05/05/2026', freq='QE')
date_range

DatetimeIndex(['2020-03-31', '2020-06-30', '2020-09-30', '2020-12-31',
               '2021-03-31', '2021-06-30', '2021-09-30', '2021-12-31',
               '2022-03-31', '2022-06-30', '2022-09-30', '2022-12-31',
               '2023-03-31', '2023-06-30', '2023-09-30', '2023-12-31',
               '2024-03-31', '2024-06-30', '2024-09-30', '2024-12-31',
               '2025-03-31', '2025-06-30', '2025-09-30', '2025-12-31',
               '2026-03-31'],
              dtype='datetime64[us]', freq='QE-DEC')

In [65]:
date_range = pd.date_range(start='01/01/2024', periods=6, tz='Asia/Tokyo')
date_range

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-01-02 00:00:00+09:00',
               '2024-01-03 00:00:00+09:00', '2024-01-04 00:00:00+09:00',
               '2024-01-05 00:00:00+09:00', '2024-01-06 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Tokyo]', freq='D')

In [66]:
start_date = '01/01/2023'
num_days = 30
date_range = pd.date_range(start=start_date, periods=num_days, freq='D')

np.random.seed(42) # seed means we are all using the Same random algorithm

stock_prices = np.random.normal(loc=100, scale=5, size=num_days).round(2)

stock_df = pd.DataFrame({'Date': date_range, 'StockPrice': stock_prices})

stock_df

         Date  StockPrice
0  2023-01-01      102.48
1  2023-01-02       99.31
2  2023-01-03      103.24
3  2023-01-04      107.62
4  2023-01-05       98.83
5  2023-01-06       98.83
6  2023-01-07      107.90
7  2023-01-08      103.84
8  2023-01-09       97.65
9  2023-01-10      102.71
10 2023-01-11       97.68
11 2023-01-12       97.67
12 2023-01-13      101.21
13 2023-01-14       90.43
14 2023-01-15       91.38
15 2023-01-16       97.19
16 2023-01-17       94.94
17 2023-01-18      101.57
18 2023-01-19       95.46
19 2023-01-20       92.94
20 2023-01-21      107.33
21 2023-01-22       98.87
22 2023-01-23      100.34
23 2023-01-24       92.88
24 2023-01-25       97.28
25 2023-01-26      100.55
26 2023-01-27       94.25
27 2023-01-28      101.88
28 2023-01-29       97.00
29 2023-01-30       98.54

In [67]:
import datetime

timestamp = pd.Timestamp('2026-05-05 13:38:00', tz='America/New_York')
print(timestamp)

dt_timestamp = datetime.datetime(2026, 5, 5, 13, 38)
print(dt_timestamp)

converted_time =timestamp.tz_convert('Asia/Tokyo')

print(converted_time)

2026-05-05 13:38:00-04:00
2026-05-05 13:38:00
2026-05-06 02:38:00+09:00

In [68]:
timestamp.year

2026

In [69]:
timestamp.dayofweek

1

In [70]:
dates = ['2026-05-05', '2024-01-13', '2025-10-10']

print(dates)
print(type(dates))

output = pd.to_datetime(dates)

print(output)

['2026-05-05', '2024-01-13', '2025-10-10']
<class 'list'>
DatetimeIndex(['2026-05-05', '2024-01-13', '2025-10-10'], dtype='datetime64[us]', freq=None)

In [71]:
input_list = ['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']

print(input_list)

output = pd.to_datetime(input_list, format='mixed')

print(output)

['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']
DatetimeIndex(['2023-01-01 00:00:00', '2023-01-02 00:00:00',
               '2020-03-10 14:30:45', '2023-10-13 00:00:00'],
              dtype='datetime64[us]', freq=None)

In [72]:
df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','Eric'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']
})

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patientID      4 non-null      int64
 1   name           4 non-null      str
 2   date_of_birth  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [73]:
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='mixed')
df.head()

   patientID     name       date_of_birth
0        101    alice 2023-01-01 00:00:00
1         23      bob 2023-01-02 00:00:00
2         48  charlie 2020-03-10 14:30:45
3         49     Eric 2023-10-13 00:00:00

In [74]:
df['date_of_birth'] = df['date_of_birth'].astype('str')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patientID      4 non-null      int64
 1   name           4 non-null      str
 2   date_of_birth  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [75]:
df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','keyla'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04']
})

df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='mixed', errors='coerce')

df

   patientID     name date_of_birth
0        101    alice    2023-01-01
1         23      bob    2023-01-02
2         48  charlie    2023-01-03
3         49    keyla    2023-01-04

In [78]:
url='https://raw.githubusercontent.com/bprasad26/lwd/master/data/tesla_stock_prices.csv'
# using parse_dates to change type from string into date
tesla_df = pd.read_csv(url)


# tesla_df.to_csv('data/tesla_stocks.csv')

tesla_df['Date'] = pd.to_datetime(tesla_df['Date']) 

tesla_df.head()

        Date       Open   High        Low      Close  Adj Close    Volume
0 2010-06-29  19.000000  25.00  17.540001  23.889999  23.889999  18766300
1 2010-06-30  25.790001  30.42  23.299999  23.830000  23.830000  17187100
2 2010-07-01  25.000000  25.92  20.270000  21.959999  21.959999   8218800
3 2010-07-02  23.000000  23.10  18.709999  19.200001  19.200001   5139800
4 2010-07-06  20.000000  20.00  15.830000  16.110001  16.110001   6866900

In [79]:
# Add new columns to dataframe based off of dates



tesla_df['Day'] = tesla_df['Date'].dt.day
tesla_df['Month'] = tesla_df['Date'].dt.month
tesla_df['Year'] = tesla_df['Date'].dt.year
tesla_df['day_name'] = tesla_df['Date'].dt.day_name()

tesla_df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume,Day,Month,Year,day_name
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,29,6,2010,Tuesday
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,30,6,2010,Wednesday
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,1,7,2010,Thursday
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,2,7,2010,Friday
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,6,7,2010,Tuesday
5,2010-07-07,16.400000,16.629999,14.980000,15.800000,15.800000,6921700,7,7,2010,Wednesday
6,2010-07-08,16.139999,17.520000,15.570000,17.459999,17.459999,7711400,8,7,2010,Thursday
7,2010-07-09,17.580000,17.900000,16.549999,17.400000,17.400000,4050600,9,7,2010,Friday
8,2010-07-12,17.950001,18.070000,17.000000,17.049999,17.049999,2202500,12,7,2010,Monday
9,2010-07-13,17.389999,18.639999,16.900000,18.139999,18.139999,2680100,13,7,2010,Tuesday

In [ ]:
least_recent = tesla_df['Date'].min()
most_recent = tesla_df['Date'].max()

print(least_recent)
print(most_recent)

2010-06-29
2017-08-08

In [80]:
monthly_sales = tesla_df.groupby(['Year', 'Month'])['Volume'].sum().reset_index()

monthly_sales.head(15)

    Year  Month    Volume
0   2010      6  35953400
1   2010      7  64575800
2   2010      8  15038200
3   2010      9  18045900
4   2010     10   6547800
5   2010     11  28315100
6   2010     12  36892900
7   2011      1  28420100
8   2011      2  29303500
9   2011      3  32563300
10  2011      4  29894900
11  2011      5  30348800
12  2011      6  39727300
13  2011      7  21102100
14  2011      8  27215700

### Filter Using loc[] or query()

In [ ]:
# filtered_df_date = tesla_df.loc[(tesla_df['Date'] >= '2010-08-01')]
filtered_df_date = tesla_df.loc[(tesla_df['Date'] >= '2010-08-01') & (tesla_df['Date'] <= '2010-12-31')]
 # created a df of a range of dates using conditions
 # conditional filtering
filtered_df_date

,Date,Open,High,Low,Close,Adj Close,Volume
23,2010-08-02,20.500000,20.969999,20.330000,20.920000,20.920000,718100
24,2010-08-03,21.000000,21.950001,20.820000,21.950001,21.950001,1230500
25,2010-08-04,21.950001,22.180000,20.850000,21.260000,21.260000,913000
26,2010-08-05,21.540001,21.549999,20.049999,20.450001,20.450001,796200
27,2010-08-06,20.100000,20.160000,19.520000,19.590000,19.590000,741900
...,...,...,...,...,...,...,...
125,2010-12-27,28.020000,28.580000,25.059999,25.549999,25.549999,9301900
126,2010-12-28,25.850000,26.750000,25.000000,26.410000,26.410000,4056300
127,2010-12-29,27.030001,28.010000,26.500000,27.730000,27.730000,3319200
128,2010-12-30,27.700001,27.900000,26.379999,26.500000,26.500000,2041100
129,2010-12-31,26.570000,27.250000,26.500000,26.629999,26.629999,1417900

In [ ]:
filtered_df = tesla_df.query("Date >= '2010-08-01' and Date <= '2010-12-31'")
filtered_df

,Date,Open,High,Low,Close,Adj Close,Volume
23,2010-08-02,20.500000,20.969999,20.330000,20.920000,20.920000,718100
24,2010-08-03,21.000000,21.950001,20.820000,21.950001,21.950001,1230500
25,2010-08-04,21.950001,22.180000,20.850000,21.260000,21.260000,913000
26,2010-08-05,21.540001,21.549999,20.049999,20.450001,20.450001,796200
27,2010-08-06,20.100000,20.160000,19.520000,19.590000,19.590000,741900
...,...,...,...,...,...,...,...
125,2010-12-27,28.020000,28.580000,25.059999,25.549999,25.549999,9301900
126,2010-12-28,25.850000,26.750000,25.000000,26.410000,26.410000,4056300
127,2010-12-29,27.030001,28.010000,26.500000,27.730000,27.730000,3319200
128,2010-12-30,27.700001,27.900000,26.379999,26.500000,26.500000,2041100
129,2010-12-31,26.570000,27.250000,26.500000,26.629999,26.629999,1417900